# Generated by Django 3.2.9 on 2021-11-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('adres', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('birh_date', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Cloth_type',
            fields=[
                ('id_cloth_type', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=45)),
                ('material', models.CharField(max_length=45)),
                ('price', models.FloatField()),
                ('manufacturer', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
                ('cloth_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id_order', models.AutoField(primary_key=True, serialize=False)),
                ('id_client', models.IntegerField()),
                ('id_item', models.IntegerField()),
            ],
        ),
    ]
