# Generated by Django 3.2.9 on 2021-11-22 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='birh_date',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='cloth_type',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cloth_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.cloth_type'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.client'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.item'),
        ),
    ]
